project:
  type: site
  output-dir: _site

execute:
  freeze: true

site:
  title: "2021 Cloud Workshop at AGU"
  site-url: https://nasa-openscapes.github.io/2021-Cloud-Workshop-AGU
  repo-url: https://github.com/nasa-openscapes/2021-Cloud-Workshop-AGU
  repo-actions: [edit, issue]
  page-navigation: true
  page-footer: "PODAAC, NSIDC DAAC and LPDAAC (2021). 2021 Cloud Workshop"
 
  navbar: 
    #background: light
    right: 
      - sidebar:welcome
      - icon: github
        href: https://github.com/nasa-openscapes/2021-Cloud-Workshop-AGU
 
  sidebar:
    - id: welcome
      title: "Menu"
      logo: https://user-images.githubusercontent.com/2915555/133525653-2a2278b1-1015-4350-b2a5-160d125aaaf7.png
      style: "docked"
      collapse-level: 1
      align: left
      contents:
        - section: "Welcome"
          contents:
            - index.md
            - cloud-paradigm.md
        - section: "Logistics"
          contents:
            - logistics/index.md
            - logistics/schedule.md
            - logistics/prerequisites.md
            - logistics/github-workflows.md
        - section: "Tutorials"
          contents: 
            - tutorials/index.md
            - tutorials/00_Setup.md  ## tutorial 0
